[package]
name = "the-crown"
version = "1.0.0"
description = "The Crown desktop wrapper"
authors = ["Ja"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]

